from aiogram.dispatcher.filters.state import StatesGroup, State


class PersonalData(StatesGroup):
    password = State()
    full_name = State()
    phone_number = State()
    questionFound1 = State()
    questionFound2 = State()
    questionFound3 = State()
    questionFound4 = State()
    questionFound5 = State()
    questionFound6 = State()
    questionFound7 = State()
    questionFound8 = State()
    questionFound9 = State()
    questionFound10 = State()
    questionFound11 = State()
    questionFound12 = State()
    questionFound13 = State()
    questionFound14 = State()
    questionFound15 = State()
    # questionDev1 = State()
    # questionDev2 = State()
    # questionDev3 = State()
    # questionDev4 = State()
    # questionDev5 = State()
    # questionDev6 = State()
    # questionDev7 = State()
    # questionDev8 = State()
    # questionDev9 = State()
    # questionDev10 = State()


class Question(StatesGroup):
    full_name = State()
    phone_number = State()
    questionFound1 = State()
    questionFound2 = State()
    questionFound3 = State()
    questionFound4 = State()
    questionFound5 = State()
    questionFound6 = State()
    questionFound7 = State()
    questionFound8 = State()
    questionFound9 = State()
    questionFound10 = State()
    questionFound11 = State()
    questionFound12 = State()
    questionFound13 = State()
    questionFound14 = State()
    questionFound15 = State()
    questionDev1 = State()
    questionDev2 = State()
    questionDev3 = State()
    questionDev4 = State()
    questionDev5 = State()
    questionDev6 = State()
    questionDev7 = State()
    questionDev8 = State()
    questionDev9 = State()
    questionDev10 = State()
